"""
Default profile data for new user registration.
Provides random default skills and professional objectives.
"""

import random

DEFAULT_OBJECTIVES = [
    "Motivated and enthusiastic individual seeking an opportunity to contribute skills, learn continuously, and grow professionally while working in a challenging and supportive environment that encourages personal and organizational success.",
    "Dedicated and hardworking professional looking for a role where I can apply my abilities, gain valuable experience, and contribute positively toward achieving organizational goals and long-term growth.",
    "Seeking a challenging opportunity in a dynamic organization where I can enhance my knowledge, improve my professional skills, and contribute effectively through dedication, teamwork, and continuous learning.",
    "Passionate and adaptable individual aiming to build a successful career by utilizing my skills, learning new technologies and processes, and contributing meaningfully to the organization's overall success.",
    "Looking for an opportunity to work in a professional environment where I can develop my capabilities, take on responsibilities, and contribute to organizational growth through commitment and consistent performance.",
    "Self-motivated and goal-oriented individual seeking a position that allows me to apply my knowledge, strengthen my skills, and grow professionally while delivering quality work and positive results.",
    "Eager to begin and grow my professional journey in an organization that values learning, innovation, teamwork, and dedication while providing opportunities for skill enhancement and career development.",
    "Seeking a responsible and growth-oriented role where I can utilize my communication, problem-solving, and teamwork skills while continuously learning and contributing effectively to business objectives.",
    "Ambitious and hardworking individual looking for a challenging role that offers opportunities to gain practical experience, improve professional expertise, and contribute positively to organizational success.",
    "To work in an organization that encourages continuous learning and professional growth, where I can apply my abilities, adapt to challenges, and contribute effectively through dedication and teamwork.",
    "Enthusiastic and detail-oriented individual seeking an opportunity to enhance my professional knowledge, develop practical experience, and contribute toward organizational goals with sincerity and commitment.",
    "Looking for a career opportunity that allows me to utilize my strengths, improve my professional capabilities, and contribute meaningfully in a collaborative and growth-focused work environment.",
    "Dedicated professional seeking a position where I can apply my skills, learn from experienced teams, and contribute effectively toward achieving organizational goals and long-term success.",
    "Seeking an opportunity to work in a challenging and innovative environment where I can continuously learn, improve my professional skills, and contribute positively through hard work and determination.",
    "Highly motivated individual aiming to build a rewarding career by contributing skills, maintaining professionalism, and continuously learning to achieve both personal and organizational growth objectives.",
]

DEFAULT_SKILLS = [
    "Communication Skills",
    "Teamwork",
    "Problem Solving",
    "Time Management",
    "Leadership",
    "Adaptability",
    "Quick Learning",
    "Multitasking",
    "Decision Making",
    "Interpersonal Skills",
    "Analytical Thinking",
    "Critical Thinking",
    "Creativity",
    "Presentation Skills",
    "Organizational Skills",
    "Professionalism",
    "Work Ethics",
    "Active Listening",
    "Customer Service",
    "Conflict Resolution",
    "Collaboration",
    "Attention to Detail",
    "Responsibility",
    "Self Motivation",
    "Positive Attitude",
    "Stress Management",
    "Flexibility",
    "Planning & Coordination",
    "Task Management",
    "Email Communication",
    "Verbal Communication",
    "Written Communication",
    "Basic Computer Knowledge",
    "MS Office",
    "Microsoft Word",
    "Microsoft Excel",
    "Microsoft PowerPoint",
    "Internet Browsing",
    "Data Entry",
    "Documentation",
    "Reporting Skills",
    "Typing Skills",
    "Research Skills",
    "Public Speaking",
    "Negotiation Skills",
    "Relationship Management",
    "Project Coordination",
    "Scheduling",
    "Client Handling",
    "Team Management",
    "Troubleshooting",
    "Process Improvement",
    "Goal Orientation",
    "Productivity Management",
    "Professional Networking",
    "Meeting Coordination",
    "Adaptability to Technology",
    "Learning Agility",
    "Operational Support",
    "Administrative Skills",
    "Strategic Thinking",
    "Business Communication",
    "Resource Management",
    "Event Coordination",
    "Observation Skills",
    "Initiative Taking",
    "Collaboration Tools Usage",
    "Virtual Meeting Handling",
    "Basic Technical Knowledge",
    "Digital Literacy",
    "AI Tool Awareness",
    "Problem Analysis",
    "Accuracy & Precision",
    "Patience",
    "Reliability",
    "Accountability",
    "Office Administration",
    "Customer Relationship Management",
    "Coordination Skills",
    "Listening Skills",
    "Cross-functional Collaboration",
    "Documentation Management",
    "Basic Presentation Design",
    "Communication Etiquette",
    "Professional Conduct",
    "Service Orientation",
    "Basic Financial Awareness",
    "Quality Focus",
    "Result Orientation",
    "Adaptability to Change",
    "Workplace Discipline",
    "Follow-up Skills",
    "Planning Skills",
    "Process Coordination",
    "Productivity Skills",
    "Knowledge Sharing",
    "Learning Mindset",
]


def get_random_default_skills(count: int = None) -> list:
    """Pick 5-6 random default skills for a new user."""
    if count is None:
        count = random.randint(5, 6)
    return random.sample(DEFAULT_SKILLS, min(count, len(DEFAULT_SKILLS)))


def get_random_objective() -> str:
    """Pick a random professional objective for a new user."""
    return random.choice(DEFAULT_OBJECTIVES)
